name: gatsby deploy

on:
  push:
    branches: [master]

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: packages install
        run: yarn install

      - name: test
        run: yarn deploy
        env:
          GH_API_KEY: ${{ secrets.API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_PAT: ${{ secrets.API_KEY }}
          BUILD_DIR: 'public/'
      
      - name: user check
        run: git config --global user.email "yunjae2295@naver.com"
      
      - name: useer name
        run: git config --global user.name "jeongyunjae"


